[0m10:57:34.762527 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002391F36C230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002391EF53260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002391F36D790>]}


============================== 10:57:34.778110 | 749d30c2-5127-4dbe-93a3-e0adcf82e190 ==============================
[0m10:57:34.778110 [info ] [MainThread]: Running with dbt=1.9.4
[0m10:57:34.778110 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\zhma\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select +demographic --full-refresh', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:57:34.778110 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\zhma\Projects\ammi\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:57:34.778110 [debug] [MainThread]: Command `dbt run` failed at 10:57:34.778110 after 0.15 seconds
[0m10:57:34.778110 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002391EF6F140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002391F729C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023919857170>]}
[0m10:57:34.778110 [debug] [MainThread]: Flushing usage events
[0m10:57:35.148761 [debug] [MainThread]: An error was encountered while trying to flush usage events
